[meta]
  title = "Prerecorded Sinatra Starter"
  description = "Basic demo for using Deepgram to transcribe files with Sinatra"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "Prerecorded"
  language = "Ruby"
  framework = "Sinatra"

[build]
  command = "bundle install"

[config]
  sample = "sample.env"
  output = ".env"

[post-build]
  message = "ruby server.rb"